#Currently this Dockerfile is supported on building on Ubuntu only.
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
	perl \
	tcsh tcl tk pciutils make lsof \
	lsb-release \
	libnuma1 \
	python-libxml2 \
	ethtool iproute2 net-tools \
	openssh-server \
	wget git \
	pkg-config bison dpatch libgfortran3 \
	kmod linux-headers-generic libnl-route-3-200 \
	swig libelf1 automake libglib2.0-0 \
	autoconf graphviz chrpath flex libnl-3-200 m4 \
	debhelper autotools-dev gfortran libltdl-dev iperf3 traceroute libfabric1
RUN apt install -y ca-certificates
RUN apt install -y linux-headers-4.9.125-linuxkit

WORKDIR /tmp/

ENV MOFED_VER 4.4-2.0.7.0
ENV OS_VER ubuntu18.04
ENV PLATFORM x86_64

RUN wget --quiet http://content.mellanox.com/ofed/MLNX_OFED-${MOFED_VER}/MLNX_OFED_LINUX-${MOFED_VER}-${OS_VER}-${PLATFORM}.tgz && \
        tar -xvf MLNX_OFED_LINUX-${MOFED_VER}-${OS_VER}-${PLATFORM}.tgz && \
        MLNX_OFED_LINUX-${MOFED_VER}-${OS_VER}-${PLATFORM}/mlnxofedinstall --user-space-only --without-fw-update --all --force

ADD entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
